### ISSUE TITLE
Marshall socket error

### ISSUE THREAD

**Issue by pagedegeek** [bluepill-rb/bluepill#22]
I have custom trigger:

```ruby
class MyNotifier < Bluepill::Trigger
require 'redis'
  def initialize(process, options = {})
    @redis = Redis.new
    super
  end
  def notify(transition)
    return if transition.from_name == transition.to_name
    msg = "Notification at [#{Time.now}] for [#{self.process.name}] #{transition.from_name} -> #{transition.to_name}"

    open('/tmp/worker.transitions.log', 'a') do |f|
      f.puts msg
    end

    @redis.lpush('transitions', msg)
  end
end
```

But runtime error:
```
/home/samuel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bluepill-0.0.68/lib/bluepill/socket.rb:22:in `load': undefined class/module Redis:: (ArgumentError)
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bluepill-0.0.68/lib/bluepill/socket.rb:22:in `block (3 levels) in client_command'
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
        from /home/samuel/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'

```

Have you an issue ?

**Comment by akzhan** [comment]
move `require 'redis'` to first line. And try to load

```ruby
require 'redis'
@redis = Redis.new
```
