### ISSUE TITLE
Bluepill and Puma won't play together

### ISSUE THREAD

**Issue by tkhduracell** [bluepill-rb/bluepill#36]
**Bluepill config**

``` rb
APP_ROOT = '/root/bytet'
REDIS_ROOT = '/usr/bin'

Bluepill.application('bytet', :log_file => "#{APP_ROOT}/tmp/logs/bluepill.log") do |app|

  app.working_dir = APP_ROOT

  app.process('puma') do |process|
    process.start_command = 'bundle exec puma -e production'
    process.pid_file = 'tmp/pids/puma.pid'

    process.deamonize = true
    process.environment = {'RAILS_ENV' => 'production'}
    process.stdout = process.stderr = 'tmp/logs/puma.log'
    process.stop_command = 'bundle exec pumactl stop --pid {{PID}}'
    process.monitor_children do |children|
      children.checks :cpu_usage,
                       :every => 10,
                       :below => 50,
                       :times => 3
      children.checks :mem_usage,
                     :every => 10,
                     :below => 300.megabytes,
                     :times => 3
    end
    process.restart_command = 'bundle exec pumactl restart --pid {{PID}}'
    process.restart_grace = 10.seconds
  end
end
```

**Logs**
Bluepill is looping these messages over and over.
`bluepill log puma`

```
W, [2015-08-07T12:06:23.581404 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
W, [2015-08-07T12:06:23.581598 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
E, [2015-08-07T12:06:23.581661 #6585] ERROR -- : [bytet:puma] Failed to signal process  with code 0: no implicit conversion from nil to integer
W, [2015-08-07T12:06:23.581753 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
W, [2015-08-07T12:06:23.581862 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
E, [2015-08-07T12:06:23.581919 #6585] ERROR -- : [bytet:puma] Failed to signal process  with code 0: no implicit conversion from nil to integer
W, [2015-08-07T12:06:23.582664 #6585]  WARN -- : [bytet:puma] Executing start command: bundle exec puma -e production
E, [2015-08-07T12:06:26.584153 #6585] ERROR -- : [bytet:puma] Execution is taking longer than expected.
E, [2015-08-07T12:06:26.584336 #6585] ERROR -- : [bytet:puma] Did you forget to tell bluepill to daemonize this process?
W, [2015-08-07T12:06:26.585035 #6585]  WARN -- : [bytet:puma] Clearing child list
I, [2015-08-07T12:06:26.585114 #6585]  INFO -- : [bytet:puma] Going from down => starting
W, [2015-08-07T12:06:29.657280 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
W, [2015-08-07T12:06:29.657467 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
E, [2015-08-07T12:06:29.657570 #6585] ERROR -- : [bytet:puma] Failed to signal process  with code 0: no implicit conversion from nil to integer
W, [2015-08-07T12:06:29.657893 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
W, [2015-08-07T12:06:29.657994 #6585]  WARN -- : [bytet:puma] pid_file /var/run/bluepill/pids/bytet/puma.pid does not exist or cannot be read
E, [2015-08-07T12:06:29.658053 #6585] ERROR -- : [bytet:puma] Failed to signal process  with code 0: no implicit conversion from nil to integer
W, [2015-08-07T12:06:29.658386 #6585]  WARN -- : [bytet:puma] Clearing child list
I, [2015-08-07T12:06:29.658479 #6585]  INFO -- : [bytet:puma] Going from starting => down
```

**Puma config**

``` rb
workers 2
threads 1, 3
preload_app!
daemonize false
rackup DefaultRackup
port        3000
environment 'production'
pidfile 'tmp/pids/puma.pid'
```

**Trying to restart**

``` rb
root@bytet:~# bluepill stop puma
/root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:21:in `load': marshal data too short (ArgumentError)
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:21:in `block (3 levels) in client_command'
    from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
    from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
    from /root/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:19:in `block (2 levels) in client_command'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:11:in `open'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:11:in `client'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:18:in `block in client_command'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:16:in `times'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/socket.rb:16:in `client_command'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/controller.rb:65:in `send_to_daemon'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/lib/bluepill/controller.rb:28:in `handle_command'
    from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bluepill-0.0.69/bin/bluepill:123:in `<top (required)>'
    from /root/.rbenv/versions/2.2.2/bin/bluepill:23:in `load'
    from /root/.rbenv/versions/2.2.2/bin/bluepill:23:in `<main>'
```

Is this a configuration error, in which a misunderstand the documentation completely?

**Comment by tkhduracell** [comment]
**Update**
Four pages of this makes me uncomfortable. 
![Lots of ruby](https://cloud.githubusercontent.com/assets/1007519/9161552/208e8798-3f42-11e5-99d3-c8f0d5f2a1f0.png)

**Comment by vladfaust** [comment]
@tkhduracell any updates here? Same issue

**Comment by tkhduracell** [comment]
No, I gave up. BluePill is awesome on the surface, but in reality not
usable.

**Comment by kellym** [comment]
Getting the same issue with a custom script to run Sidekiq. Oddly enough, we're using Chef and have the exact same code on two servers -- one server is fine, one throws this odd error.

**Comment by kellym** [comment]
After spending hours debugging and then finally commenting here, it only took me another 5 minutes to realize the `/run` disk where the PID is stored is full. Making sure there's access to the right PID file seems to be related.

**Comment by tkhduracell** [comment]
Great! Would you mind updating so that appropriate errors are thrown?

**Comment by eltone** [comment]
@tkhduracell I know this issue is very old but had you noticed that `process.deamonize = true` contains a spelling mistake?

**Comment by tkhduracell** [comment]
@eltone Thanks, that might be the thing. Some validation would be nice however.
