### ISSUE TITLE
TypeError: No implicit conversion of false into Integer

### ISSUE THREAD

**Issue by redox** [bluepill-rb/bluepill#38]
I get the follow error when trying to start/quit a bluepill process that is not yet running yet.

```
 /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/system.rb:23:in `kill' : no implicit conversion of false into Integer (TypeError)
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/system.rb:23:in `pid_alive?'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/controller.rb:89:in `block in cleanup_bluepill_directory'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/controller.rb:87:in `each'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/controller.rb:87:in `cleanup_bluepill_directory'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/lib/bluepill/controller.rb:15:in `initialize'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/bin/bluepill:77:in `new'
 from /somewhere/shared/bundle/ruby/2.1.0/gems/bluepill-0.0.70/bin/bluepill:77:in `<top (required)>'
 from /somewhere/shared/bundle/ruby/2.1.0/bin/bluepill:23:in `load'
 from /somewhere/shared/bundle/ruby/2.1.0/bin/bluepill:23:in `<main>'
```

Reading the code, I assume the following test `next if pid || System.pid_alive?(pid)` (https://github.com/bluepill-rb/bluepill/blob/master/lib/bluepill/controller.rb#L89) should rather use `&&` then `||`, right? -> otherwise we're potentially calling `pid_alive?` with `false` :/

(Using bluepill 0.70 & ruby 2.1)

**Comment by spodlecki** [comment]
Anything happen with this ?

**Comment by rriemann** [comment]
changing `||`to `&&` is fixing the following error for me:

```
/var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/system.rb:23:in `kill': no implicit conversion of false into Integer (TypeError)
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/system.rb:23:in `pid_alive?'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/controller.rb:89:in `block in cleanup_bluepill_directory'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/controller.rb:87:in `each'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/controller.rb:87:in `cleanup_bluepill_directory'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/lib/bluepill/controller.rb:15:in `initialize'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/bin/bluepill:77:in `new'
        from /var/lib/gems/2.1.0/gems/bluepill-0.1.1/bin/bluepill:77:in `<top (required)>'
        from /usr/local/bin/bluepill:23:in `load'
        from /usr/local/bin/bluepill:23:in `<main>'
```

**Comment by redox** [comment]
Thanks @akzhan 👍

**Comment by spodlecki** [comment]
👍 @akzhan
